### Comando magico:

comando di jupyter: quanto tempo impiega una cella a girare
iniziano con % a inizio cella
quando uso i comandi magici perdo il valore delle variabili

In [10]:
%%timeit
quadrati=[]

for i in range(1,10000):
    quadrati.append(i**2)

2.25 ms ± 327 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
quadrati

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

valor medio 
deviazione standard: quanto i voti sono concentrati alla media
jupyter lo esegue più volte e ogni volta misura il tempo e fa la media

### NumPY
non è nativo=non incluso python, ma anaconda lo contiene

In [12]:
import numpy as np #alias: standard

## Introduzione a NumPy
si basa sugli array (ndarray)
in python non esistono (le liste non sono array)
per fare un array: gli elementi devono essere dello stesso tipo


### Creazione array a 1 dimensione

In [13]:
# array di zeri
array_di_zery=np.zeros(10)
array_di_zery

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#array è un oggetto di numpy di float a 64 bit
array_di_zery.dtype

dtype('float64')

In [24]:
array_di_zery_interi=np.zeros(10, dtype=np.int8) #numpy ha diversi tipi
array_di_zery_interi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [22]:
# array di uni
array_di_uni=np.ones(5)
array_di_uni

array([1., 1., 1., 1., 1.])

In [28]:
#array di tre:
array_di_tre=np.ones(10, dtype=np.int8)*3
#broadcast
#quando moltiplico un array di numpy per un numero la moltiplicazione viene fatta elemento per elemento
#broadcast: operazione fatta su tutti gli elementi

In [29]:
array_di_tre

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int8)

In [30]:
#array di numeri interi crescenti
array_numeri_crescenti=np.arange(1,10)
array_numeri_crescenti

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
%%timeit
array_quadrati=np.arange(1,10000)**2

25.5 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [34]:
array_quadrati #altra operazione di broadcast

array([       1,        4,        9, ..., 99940009, 99960004, 99980001])